/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wooden_chair.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wooden_chair.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.377, 0, 2.032]}>
        <mesh geometry={nodes.arm.geometry} material={materials['chair-wood']} position={[0.733, 0.003, -2.079]} rotation={[0, 0.327, 0.172]}>
          <mesh geometry={nodes['back-slat'].geometry} material={materials['chair-wood']} position={[-0.233, 0.152, -0.587]} rotation={[0, 0, -0.172]} />
          <mesh geometry={nodes.front_slat.geometry} material={materials['chair-wood']} position={[-0.233, 0.152, -0.214]} rotation={[0, 0, -0.172]} />
          <mesh geometry={nodes.lower_screw_bottom.geometry} material={materials.screw} position={[-0.375, 0.397, -0.039]} rotation={[-0.05, 0.013, -0.355]} />
          <mesh geometry={nodes.lower_screw_top.geometry} material={materials.screw} position={[-0.315, 0.635, -0.367]} rotation={[1.34, 0.43, -0.136]} />
          <mesh geometry={nodes.lower_seat.geometry} material={materials['chair-wood']} position={[-0.251, 0.045, -0.223]} rotation={[0, 0, -0.172]} />
          <mesh geometry={nodes.upper_screw_bottom.geometry} material={materials.screw} position={[-0.392, 0.39, -0.254]} rotation={[-0.054, 0.014, -0.345]} />
          <mesh geometry={nodes.upper_screw_top.geometry} material={materials.screw} position={[-0.286, 0.786, -0.415]} rotation={[1.32, 0.43, -0.15]} />
          <mesh geometry={nodes.upper_seat.geometry} material={materials['chair-wood']} position={[-0.14, 0.683, -0.424]} rotation={[1.216, -0.162, -0.059]} />
        </mesh>
      </group>
      <pointLight intensity={5.2} decay={2} position={[-0.476, 1.448, 0.702]} />
      <pointLight intensity={2.18} decay={2} position={[0.102, 0.135, -1.266]} />
    </group>
  )
}

useGLTF.preload('/wooden_chair.gltf')
